# @package _global_
model:
  name: model7_A
  pretrained: false
  num_classes: ${num_classes}
  # Doit matcher EXACTEMENT le pretrain VideoMAEv2 pour le load à 100 %
  img_size: 224
  tubelet_t: 2
  patch_size: 16
  in_chans: 3
  embed_dim: 768
  depth: 12
  n_heads: 12
  mlp_ratio: 4
  # Regularisation finetune
  dropout: 0.0
  drop_path_rate: 0.2     # paper: 0.1-0.2 pour ViT-B/16 en finetune MAE
  head_dropout: 0.0
  pool: avg               # 'avg' (recommandé VideoMAE) ou 'cls'
